[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "haxmas-day-9-rmardia"
version = "0.0.1"
dependencies = ["textual"]

[project.scripts]
advent-calender = "haxmas_day_9_rmardia.main:main"

[tool.hatch.build.targets.wheel]
packages = ["haxmas_day_9_rmardia"]