build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "haxmas_day_9_YOUR_USERNAME"
version = "0.0.1"
dependencies = [
    "textual",
]

[project.scripts]
advent-calendar = "haxmas_day_9_YOUR_USERNAME.main:main"
